"""sync models clean

Revision ID: fe1da6774091
Revises: 804dc44de534
Create Date: 2025-11-27 18:49:50.241116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1da6774091'
down_revision: Union[str, Sequence[str], None] = '804dc44de534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coworker_invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('coworker_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coworker_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_coworker_invite_codes_id'), 'coworker_invite_codes', ['id'], unique=False)
    op.add_column('otp_codes', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_constraint(op.f('uq_phone_code'), 'otp_codes', type_='unique')
    op.create_unique_constraint('uq_phone_code', 'otp_codes', ['phone_number', 'code'])
    op.create_index(op.f('ix_otp_codes_phone_number'), 'otp_codes', ['phone_number'], unique=False)
    op.drop_column('otp_codes', 'phone')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('otp_codes', sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_otp_codes_phone_number'), table_name='otp_codes')
    op.drop_constraint('uq_phone_code', 'otp_codes', type_='unique')
    op.create_unique_constraint(op.f('uq_phone_code'), 'otp_codes', ['phone', 'code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.drop_column('otp_codes', 'phone_number')
    op.drop_index(op.f('ix_coworker_invite_codes_id'), table_name='coworker_invite_codes')
    op.drop_table('coworker_invite_codes')
    # ### end Alembic commands ###
